name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }}, thank you for taking your time and submitting an issue. We appreciate the help!'
        pr-message: 'Hello @${{ github.actor }}, thank you for taking your time and submitting a pull request. We appreciate the help!'
